const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1'
async function request(path,options={}){const response=await fetch(`${API_BASE}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!response.ok){const payload=await response.json().catch(()=>({}));const error=new Error(payload.detail||`Request failed (${response.status})`);error.status=response.status;throw error}if(response.status===204)return null;return response.json()}
export const api={
me:()=>request('/auth/me'),login:(email,password)=>request('/auth/login',{method:'POST',body:JSON.stringify({email,password})}),logout:()=>request('/auth/logout',{method:'POST'}),
conversations:(assignment='all')=>request(`/conversations?assignment=${encodeURIComponent(assignment)}`),messages:id=>request(`/conversations/${id}/messages`),markRead:id=>request(`/conversations/${id}/read`,{method:'POST'}),setConversationStatus:(id,status)=>request(`/conversations/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),assignConversation:(id,userId)=>request(`/conversations/${id}/assignment`,{method:'PATCH',body:JSON.stringify({user_id:userId})}),sendText:(id,text)=>request(`/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({text})}),
contacts:(query='',tagId=null,lifecycle='active')=>{const params=new URLSearchParams();if(query)params.set('q',query);if(tagId)params.set('tag_id',tagId);if(lifecycle)params.set('lifecycle',lifecycle);const suffix=params.toString()?`?${params}`:'';return request(`/contacts${suffix}`)},contact:id=>request(`/contacts/${id}`),updateContact:(id,payload)=>request(`/contacts/${id}`,{method:'PATCH',body:JSON.stringify(payload)}),updateContactLifecycle:(id,payload)=>request(`/contacts/${id}/lifecycle`,{method:'PATCH',body:JSON.stringify(payload)}),
contactTags:()=>request('/contacts/tags'),createContactTag:name=>request('/contacts/tags',{method:'POST',body:JSON.stringify({name})}),addContactTag:(cid,tid)=>request(`/contacts/${cid}/tags/${tid}`,{method:'POST'}),removeContactTag:(cid,tid)=>request(`/contacts/${cid}/tags/${tid}`,{method:'DELETE'}),addContactNote:(id,body)=>request(`/contacts/${id}/notes`,{method:'POST',body:JSON.stringify({body})}),deleteContactNote:(cid,nid)=>request(`/contacts/${cid}/notes/${nid}`,{method:'DELETE'}),
contactFields:()=>request('/contact-fields'),createContactField:payload=>request('/contact-fields',{method:'POST',body:JSON.stringify(payload)}),updateContactField:(id,payload)=>request(`/contact-fields/${id}`,{method:'PATCH',body:JSON.stringify(payload)}),deleteContactField:id=>request(`/contact-fields/${id}`,{method:'DELETE'}),contactCustomFields:id=>request(`/contacts/${id}/custom-fields`),setContactCustomField:(cid,fid,value)=>request(`/contacts/${cid}/custom-fields/${fid}`,{method:'PUT',body:JSON.stringify({value})}),
users:()=>request('/users'),agents:()=>request('/users/agents'),createUser:payload=>request('/users',{method:'POST',body:JSON.stringify(payload)}),updateUser:(id,payload)=>request(`/users/${id}`,{method:'PATCH',body:JSON.stringify(payload)}),whatsappConnections:()=>request('/settings/whatsapp'),webhookSetup:()=>request('/settings/whatsapp/webhook'),verifyWhatsApp:payload=>request('/settings/whatsapp/verify',{method:'POST',body:JSON.stringify(payload)}),whatsappHealth:id=>request(`/settings/whatsapp/${id}/health`),connectWhatsApp:payload=>request('/settings/whatsapp',{method:'POST',body:JSON.stringify(payload)})}
