<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { api } from './api'

const props = defineProps({ currentUser: { type: Object, required: true } })
const emit = defineEmits(['logout'])
const view = ref('inbox')
const conversations = ref([]), messages = ref([]), connections = ref([]), agents = ref([]), users = ref([])
const selectedId = ref(null), loading = ref(false), sending = ref(false), savingConnection = ref(false), testingConnection = ref(false), changingStatus = ref(false), assigning = ref(false), savingUser = ref(false)
const error = ref(''), success = ref(''), reply = ref(''), messagePane = ref(null), webhook = ref(null), preview = ref(null), health = ref({}), inboxFilter = ref('all'), assignmentFilter = ref('all')
const connectionForm = ref({ workspace_name: 'Default Workspace', workspace_slug: 'default', waba_id: '', phone_number_id: '', access_token: '' })
const userForm = ref({ email: '', name: '', password: '', role: 'agent' })
const selectedConversation = computed(() => conversations.value.find((item) => item.id === selectedId.value) || null)
const filteredConversations = computed(() => inboxFilter.value === 'all' ? conversations.value : conversations.value.filter((item) => item.status === inboxFilter.value))
const totalUnread = computed(() => conversations.value.reduce((total, item) => total + (item.unread_count || 0), 0))
const canManageUsers = computed(() => props.currentUser.role === 'admin')
const canManageSettings = computed(() => props.currentUser.role === 'admin')
const canAssignOthers = computed(() => ['admin','manager'].includes(props.currentUser.role))
let inboxTimer = null

async function scrollToBottom(){ await nextTick(); if(messagePane.value) messagePane.value.scrollTop=messagePane.value.scrollHeight }
async function loadConversations({silent=false, autoSelect=true}={}){ try{ const latest=await api.conversations(assignmentFilter.value); conversations.value=latest; if(autoSelect&&!selectedId.value&&latest.length) await selectConversation(latest[0].id); else if(selectedId.value&&!latest.some((item)=>item.id===selectedId.value)){selectedId.value=null;messages.value=[]} }catch(err){if(!silent)error.value=err.message} }
async function changeAssignmentFilter(filter){ assignmentFilter.value=filter; selectedId.value=null; messages.value=[]; await loadConversations() }
async function selectConversation(id){ selectedId.value=id; loading.value=true; error.value=''; try{messages.value=await api.messages(id);await api.markRead(id);await loadConversations({silent:true,autoSelect:false});await scrollToBottom()}catch(err){error.value=err.message}finally{loading.value=false} }
async function refreshInbox(){ if(view.value!=='inbox'||loading.value||sending.value)return; try{ await loadConversations({silent:true,autoSelect:false}); if(selectedId.value){ const latest=await api.messages(selectedId.value); const changed=latest.length!==messages.value.length||latest.some((item,index)=>item.id!==messages.value[index]?.id||item.status!==messages.value[index]?.status); if(changed){messages.value=latest;await api.markRead(selectedId.value);await loadConversations({silent:true,autoSelect:false});await scrollToBottom()} } }catch(_){} }
async function sendReply(){ const c=selectedConversation.value,text=reply.value.trim(); if(!c||!text||sending.value)return; sending.value=true;error.value='';try{const m=await api.sendText(c.id,text);messages.value.push(m);reply.value='';await loadConversations({silent:true,autoSelect:false});await scrollToBottom()}catch(err){error.value=err.message}finally{sending.value=false} }
async function changeStatus(status){const c=selectedConversation.value;if(!c||changingStatus.value)return;changingStatus.value=true;error.value='';try{await api.setConversationStatus(c.id,status);await loadConversations({silent:true,autoSelect:false})}catch(err){error.value=err.message}finally{changingStatus.value=false}}
async function assignConversation(userId){const c=selectedConversation.value;if(!c||assigning.value)return;assigning.value=true;error.value='';try{await api.assignConversation(c.id,userId===null?null:Number(userId));await loadConversations({silent:true,autoSelect:false})}catch(err){error.value=err.message}finally{assigning.value=false}}
async function takeConversation(){await assignConversation(props.currentUser.id)}
async function openInbox(){view.value='inbox';error.value='';success.value='';try{agents.value=await api.agents();await loadConversations({autoSelect:false})}catch(err){error.value=err.message}}
async function openUsers(){if(!canManageUsers.value)return;view.value='users';error.value='';success.value='';try{users.value=await api.users()}catch(err){error.value=err.message}}
async function createUser(){if(savingUser.value)return;savingUser.value=true;error.value='';success.value='';try{const created=await api.createUser(userForm.value);users.value.push(created);agents.value=await api.agents();userForm.value={email:'',name:'',password:'',role:'agent'};success.value='User created successfully.'}catch(err){error.value=err.message}finally{savingUser.value=false}}
async function updateUser(user, changes){error.value='';success.value='';try{const updated=await api.updateUser(user.id,changes);const index=users.value.findIndex((item)=>item.id===user.id);if(index>=0)users.value[index]=updated;agents.value=await api.agents();success.value='User updated.'}catch(err){error.value=err.message}}
async function openSettings(){ if(!canManageSettings.value)return;view.value='settings';error.value='';success.value='';try{[connections.value,webhook.value]=await Promise.all([api.whatsappConnections(),api.webhookSetup()])}catch(err){error.value=err.message} }
async function testConnection(){ testingConnection.value=true;error.value='';success.value='';preview.value=null;try{preview.value=await api.verifyWhatsApp({waba_id:connectionForm.value.waba_id,phone_number_id:connectionForm.value.phone_number_id,access_token:connectionForm.value.access_token});success.value='Meta connection verified successfully.'}catch(err){error.value=err.message}finally{testingConnection.value=false} }
async function saveConnection(){ if(savingConnection.value)return;savingConnection.value=true;error.value='';success.value='';try{const created=await api.connectWhatsApp(connectionForm.value);connections.value.push(created);preview.value=null;connectionForm.value={...connectionForm.value,waba_id:'',phone_number_id:'',access_token:''};success.value='WhatsApp Business number verified and connected.'}catch(err){error.value=err.message}finally{savingConnection.value=false} }
async function checkHealth(connection){ health.value={...health.value,[connection.id]:{loading:true}};try{health.value={...health.value,[connection.id]:await api.whatsappHealth(connection.id)}}catch(err){health.value={...health.value,[connection.id]:{connected:false,error:err.message}}} }
function formatTime(value){if(!value)return'';return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function formatListTime(value){if(!value)return'';const date=new Date(value),today=new Date();if(date.toDateString()===today.toDateString())return formatTime(value);return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(date)}
onMounted(async()=>{try{agents.value=await api.agents()}catch(_){};await loadConversations();inboxTimer=window.setInterval(refreshInbox,3000)})
onBeforeUnmount(()=>{if(inboxTimer)window.clearInterval(inboxTimer)})
</script>

<template>
<main class="shell" :class="{'wide-view':view!=='inbox'}">
<aside class="sidebar"><div class="brand"><div class="logo">WA</div><div><strong>WA Connect</strong><span>WhatsApp Core v0.1.0</span></div></div><nav class="nav"><button :class="{active:view==='inbox'}" @click="openInbox">Inbox <b v-if="totalUnread" class="nav-badge">{{totalUnread}}</b></button><button disabled>Contacts</button><button disabled>Flows</button><button disabled>Campaigns</button><button v-if="canManageUsers" :class="{active:view==='users'}" @click="openUsers">Users</button><button v-if="canManageSettings" :class="{active:view==='settings'}" @click="openSettings">Settings</button></nav><div class="sidebar-user"><span class="avatar">{{currentUser.name.slice(0,1).toUpperCase()}}</span><div><strong>{{currentUser.name}}</strong><small>{{currentUser.role}}</small></div><button title="Log out" @click="emit('logout')">↪</button></div></aside>
<template v-if="view==='inbox'">
<section class="conversation-list"><header><div><p class="eyebrow">Live chat</p><h1>Inbox <span v-if="totalUnread" class="title-badge">{{totalUnread}}</span></h1></div><button class="refresh" @click="loadConversations">↻</button></header><div class="assignment-filters"><button v-for="filter in ['all','mine','unassigned']" :key="filter" :class="{active:assignmentFilter===filter}" @click="changeAssignmentFilter(filter)">{{filter}}</button></div><div class="filters"><button v-for="filter in ['all','open','pending','resolved']" :key="filter" :class="{active:inboxFilter===filter}" @click="inboxFilter=filter">{{filter}}</button></div><div v-if="!filteredConversations.length" class="empty-list">No conversations in this view.</div><button v-for="c in filteredConversations" :key="c.id" class="conversation-row" :class="{selected:selectedId===c.id,unread:c.unread_count>0}" @click="selectConversation(c.id)"><span class="avatar">{{(c.contact.name||c.contact.wa_id).slice(0,1).toUpperCase()}}</span><span class="conversation-copy"><span class="row-top"><strong>{{c.contact.name||c.contact.wa_id}}</strong><time>{{formatListTime(c.last_message_at)}}</time></span><span class="row-bottom"><small>{{c.last_message_direction==='outbound'?'You: ':''}}{{c.last_message_body||c.contact.wa_id}}</small><b v-if="c.unread_count" class="unread-badge">{{c.unread_count}}</b></span><span class="assignee-line">{{c.assigned_user ? c.assigned_user.name : 'Unassigned'}}</span></span></button></section>
<section class="chat-panel"><template v-if="selectedConversation"><header class="chat-header"><div><strong>{{selectedConversation.contact.name||selectedConversation.contact.wa_id}}</strong><span>{{selectedConversation.contact.wa_id}}</span></div><div class="header-actions"><select v-if="canAssignOthers" :value="selectedConversation.assigned_user_id||''" :disabled="assigning" @change="assignConversation($event.target.value ? Number($event.target.value) : null)"><option value="">Unassigned</option><option v-for="agent in agents" :key="agent.id" :value="agent.id">{{agent.name}}</option></select><button v-else-if="!selectedConversation.assigned_user_id" class="take-button" :disabled="assigning" @click="takeConversation">Take conversation</button><span v-else class="agent-pill">{{selectedConversation.assigned_user?.name}}</span><select :value="selectedConversation.status" :disabled="changingStatus" @change="changeStatus($event.target.value)"><option value="open">Open</option><option value="pending">Pending</option><option value="resolved">Resolved</option></select></div></header><div ref="messagePane" class="messages"><div v-if="loading" class="center-state">Loading messages…</div><article v-for="m in messages" :key="m.id" class="bubble" :class="m.direction"><p>{{m.body||`[${m.message_type}]`}}</p><footer><span>{{formatTime(m.whatsapp_timestamp||m.created_at)}}</span><span>{{m.status}}</span></footer></article></div><form class="composer" @submit.prevent="sendReply"><textarea v-model="reply" rows="1" placeholder="Type a WhatsApp reply…" @keydown.enter.exact.prevent="sendReply"/><button :disabled="sending||!reply.trim()">{{sending?'Sending…':'Send'}}</button></form></template><div v-else class="center-state">Select a conversation to start chatting.</div><div v-if="error" class="error-banner">{{error}}</div></section>
<aside class="contact-panel"><template v-if="selectedConversation"><div class="large-avatar">{{(selectedConversation.contact.name||selectedConversation.contact.wa_id).slice(0,1).toUpperCase()}}</div><h2>{{selectedConversation.contact.name||'WhatsApp Contact'}}</h2><p>{{selectedConversation.contact.wa_id}}</p><hr/><dl><div><dt>Assigned to</dt><dd>{{selectedConversation.assigned_user?.name||'Unassigned'}}</dd></div><div><dt>Status</dt><dd>{{selectedConversation.status}}</dd></div><div><dt>Unread</dt><dd>{{selectedConversation.unread_count}}</dd></div><div><dt>Channel</dt><dd>WhatsApp</dd></div></dl><button v-if="!selectedConversation.assigned_user_id" class="take-wide" @click="takeConversation">Take conversation</button><div class="status-actions"><button @click="changeStatus('open')">Open</button><button @click="changeStatus('pending')">Pending</button><button @click="changeStatus('resolved')">Resolve</button></div></template></aside>
</template>
<section v-else-if="view==='users'" class="settings-page"><header class="settings-header"><div><p class="eyebrow">Team</p><h1>Users</h1><p>Create agents and managers, control access and reset passwords.</p></div></header><div class="settings-grid"><form class="settings-card" @submit.prevent="createUser"><h2>Add user</h2><div class="form-grid"><label>Name<input v-model="userForm.name" required/></label><label>Email<input v-model="userForm.email" type="email" required/></label><label>Role<select v-model="userForm.role"><option value="agent">Agent</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label><label>Password<input v-model="userForm.password" type="password" minlength="8" required autocomplete="new-password"/></label></div><button class="primary" :disabled="savingUser">{{savingUser?'Creating…':'Create user'}}</button><p v-if="success" class="success-message">{{success}}</p><p v-if="error" class="form-error">{{error}}</p></form><div class="settings-card wide-card"><h2>Team members</h2><article v-for="member in users" :key="member.id" class="user-row"><span class="avatar">{{member.name.slice(0,1).toUpperCase()}}</span><div class="user-copy"><strong>{{member.name}}</strong><span>{{member.email}}</span></div><select :value="member.role" :disabled="member.id===currentUser.id" @change="updateUser(member,{role:$event.target.value})"><option value="agent">Agent</option><option value="manager">Manager</option><option value="admin">Admin</option></select><button class="secondary" :disabled="member.id===currentUser.id" @click="updateUser(member,{active:!member.active})">{{member.active?'Deactivate':'Activate'}}</button><span class="status-pill" :class="{inactive:!member.active}">{{member.active?'active':'inactive'}}</span></article></div></div></section>
<section v-else-if="canManageSettings" class="settings-page"><header class="settings-header"><div><p class="eyebrow">Configuration</p><h1>WhatsApp Business</h1><p>Verify Meta credentials, connect a number and monitor its connection health.</p></div></header><div class="settings-grid"><form class="settings-card" @submit.prevent="saveConnection"><h2>Connect number</h2><p class="muted">WA Connect verifies these IDs against Meta before saving anything.</p><div class="form-grid"><label>Workspace name<input v-model="connectionForm.workspace_name" required/></label><label>Workspace slug<input v-model="connectionForm.workspace_slug" required/></label><label>WABA ID<input v-model="connectionForm.waba_id" required/></label><label>Phone number ID<input v-model="connectionForm.phone_number_id" required/></label><label class="wide">Permanent access token<input v-model="connectionForm.access_token" type="password" required autocomplete="off"/></label></div><div class="button-row"><button type="button" class="secondary" :disabled="testingConnection" @click="testConnection">{{testingConnection?'Testing…':'Test Meta connection'}}</button><button class="primary" :disabled="savingConnection">{{savingConnection?'Connecting…':'Verify & connect'}}</button></div><div v-if="preview" class="meta-preview"><strong>{{preview.verified_name||preview.account_name}}</strong><span>{{preview.display_phone_number}}</span><small>Quality: {{preview.quality_rating||'n/a'}} · Platform: {{preview.platform_type||'n/a'}}</small></div><p v-if="success" class="success-message">{{success}}</p><p v-if="error" class="form-error">{{error}}</p></form><div class="settings-card"><h2>Meta webhook</h2><dl v-if="webhook" class="setup-list"><div><dt>Callback path</dt><dd><code>{{webhook.callback_path}}</code></dd></div><div><dt>Verify token</dt><dd><code>{{webhook.verify_token}}</code></dd></div><div><dt>App secret</dt><dd>{{webhook.app_secret_configured?'Configured':'Not configured'}}</dd></div></dl></div><div class="settings-card wide-card"><h2>Connected numbers</h2><article v-for="c in connections" :key="c.id" class="connection-row"><div><strong>{{c.verified_name||c.account_name||c.display_phone_number||c.phone_number_id}}</strong><span>{{c.display_phone_number}}</span></div><div class="connection-meta"><span class="status-pill">{{c.active?'active':'inactive'}}</span><small>WABA {{c.waba_id}}</small></div><div class="health-actions"><button class="secondary" @click="checkHealth(c)">{{health[c.id]?.loading?'Checking…':'Check Meta'}}</button><small v-if="health[c.id]?.connected" class="health-ok">Connected · {{health[c.id].quality_rating||'quality n/a'}}</small></div></article></div></div></section>
<section v-else class="settings-page"><div class="center-state">You do not have access to this area.</div></section></main>
</template>