<script setup>
import { computed } from 'vue'
import CustomFieldSelector from './CustomFieldSelector.vue'
const props=defineProps({draft:{type:Object,required:true},tags:{type:Array,default:()=>[]},fields:{type:Array,default:()=>[]},agents:{type:Array,default:()=>[]}})
const emit=defineEmits(['field-created'])
const operators=computed(()=>{switch(props.draft.condition_field){case'service_window':return[['open','Open'],['closed','Closed']];case'assigned_user':return[['equals','Is'],['not_equals','Is not'],['empty','Unassigned'],['not_empty','Assigned']];case'tag':return[['equals','Has tag'],['not_equals','Does not have tag'],['empty','Has no tags'],['not_empty','Has any tag']];case'conversation_status':return[['equals','Is'],['not_equals','Is not']];case'custom_field':return[['equals','Equals'],['not_equals','Does not equal'],['contains','Contains'],['not_contains','Does not contain'],['starts_with','Starts with'],['ends_with','Ends with'],['empty','Is empty'],['not_empty','Is not empty']];default:return[['equals','Equals'],['not_equals','Not equals']]}})
const needsValue=computed(()=>!['service_window'].includes(props.draft.condition_field)&&!['empty','not_empty'].includes(props.draft.operator)),needsCustomValue=computed(()=>props.draft.condition_field==='custom_field'&&!['empty','not_empty'].includes(props.draft.operator))
const checkMeta=computed(()=>({service_window:['◷','Service window','Branch according to the WhatsApp 24-hour customer service window.'],tag:['🏷','Contact tag','Branch according to labels currently assigned to the contact.'],custom_field:['▤','Custom field','Compare a stored contact field against a value.'],conversation_status:['✓','Conversation status','Branch according to the current live-chat status.'],assigned_user:['♟','Assigned agent','Branch according to who owns the conversation.']}[props.draft.condition_field]||['⌘','Condition','Choose what this condition should evaluate.']))
function changed(){if(props.draft.condition_field==='service_window'){props.draft.operator='open';props.draft.value=''}else if(props.draft.condition_field==='assigned_user'){props.draft.operator='equals';props.draft.value=''}else if(props.draft.condition_field==='tag'){props.draft.operator='equals';props.draft.value=''}else if(props.draft.condition_field==='conversation_status'){props.draft.operator='equals';props.draft.value='open'}else if(props.draft.condition_field==='custom_field'){props.draft.operator='equals';props.draft.custom_field_key='';props.draft.compare_value='';props.draft.value=''}}
function operatorChanged(){if(['empty','not_empty'].includes(props.draft.operator))props.draft.value=''}
</script>
<template><div class="condition-editor">
<div class="condition-intro"><span class="intro-icon">⌘</span><div><b>Condition rule</b><small>Choose the data to check, how it should be compared, and the value to match.</small></div></div>
<div class="condition-card">
 <div class="card-head"><span class="card-icon">{{checkMeta[0]}}</span><div><b>{{checkMeta[1]}}</b><small>{{checkMeta[2]}}</small></div></div>
 <div class="rule-grid">
  <label class="field check-field"><span>Check</span><select v-model="draft.condition_field" @change="changed"><option value="service_window">24-hour service window</option><option value="tag">Contact tag</option><option value="custom_field">Custom field</option><option value="conversation_status">Conversation status</option><option value="assigned_user">Assigned agent</option></select></label>
  <label class="field operator-field"><span>Operator</span><select v-model="draft.operator" @change="operatorChanged"><option v-for="([value,label]) in operators" :key="value" :value="value">{{label}}</option></select></label>
  <label v-if="draft.condition_field==='assigned_user'&&needsValue" class="field value-field"><span>Agent</span><select v-model="draft.value"><option value="">Select an agent…</option><option v-for="agent in agents" :key="agent.id" :value="String(agent.id)">{{agent.name||agent.email}}</option></select></label>
  <label v-else-if="draft.condition_field==='tag'&&needsValue" class="field value-field"><span>Tag</span><select v-model="draft.value"><option value="">Select a tag…</option><option v-for="tag in tags" :key="tag.id" :value="tag.name">{{tag.name}}</option></select></label>
  <label v-else-if="draft.condition_field==='conversation_status'" class="field value-field"><span>Status</span><select v-model="draft.value"><option value="open">Open</option><option value="pending">Pending</option><option value="resolved">Resolved</option></select></label>
 </div>
 <label v-if="draft.condition_field==='custom_field'" class="field custom-field"><span>Custom field</span><CustomFieldSelector v-model="draft.custom_field_key" :fields="fields" value-mode="key" @field-created="emit('field-created',$event)"/></label>
 <label v-if="needsCustomValue" class="field custom-value"><span>Comparison value</span><input v-model="draft.compare_value" placeholder="Enter value to compare against"></label>
 <div v-if="draft.condition_field==='service_window'" class="condition-help"><b>Branch behaviour</b><span>True follows the branch when the WhatsApp 24-hour customer service window is {{draft.operator==='open'?'open':'closed'}}.</span></div>
 <div v-else-if="['empty','not_empty'].includes(draft.operator)" class="condition-help"><b>No value required</b><span>This operator only checks whether data is present.</span></div>
</div>
</div></template>
<style scoped>
.condition-editor{display:flex;flex-direction:column;gap:14px}.condition-intro{display:flex;gap:11px;align-items:center;padding:13px 14px;border:1px solid #e1e9e6;border-radius:11px;background:#fbfcfc}.intro-icon,.card-icon{display:grid;place-items:center;flex:0 0 auto;width:34px;height:34px;border-radius:9px;background:#eaf8f2;color:#13845f;font-weight:800}.condition-intro b,.condition-intro small,.card-head b,.card-head small{display:block}.condition-intro b,.card-head b{font-size:14px}.condition-intro small,.card-head small{margin-top:2px;color:#74857e;font-size:11px;line-height:1.35}.condition-card{padding:14px;border:1px solid #dfe8e4;border-radius:12px;background:#fff;box-shadow:0 1px 2px rgba(20,55,43,.025)}.card-head{display:flex;gap:10px;align-items:center;margin-bottom:15px;padding-bottom:13px;border-bottom:1px solid #edf1ef}.rule-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,.85fr);gap:12px}.field{display:flex;flex-direction:column;gap:6px;margin:0 0 12px;font-size:12px;font-weight:700;color:#263c34}.field>span{font-size:11px}.field select,.field input{width:100%;min-height:40px;box-sizing:border-box;border:1px solid #d4dfda;border-radius:8px;padding:8px 10px;background:#fff;color:#1f302a;font:inherit;outline:none}.field select:focus,.field input:focus{border-color:#1a9b70;box-shadow:0 0 0 3px rgba(26,155,112,.09)}.value-field{grid-column:1/-1}.custom-field,.custom-value{margin-top:2px}.condition-help{display:flex;flex-direction:column;gap:3px;margin-top:2px;padding:11px 12px;border-radius:8px;background:#eff8f4;color:#526b61;font-size:11px;line-height:1.45}.condition-help b{color:#27735b}.condition-help span{display:block}@media(max-width:520px){.rule-grid{grid-template-columns:1fr}.value-field{grid-column:auto}}
</style>