<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { api } from './api'

const props = defineProps({ contact: { type: Object, default: null }, admin: { type: Boolean, default: false } })
const fields = ref([]), values = reactive({}), loading = ref(false), saving = ref({}), error = ref(''), success = ref('')
const form = reactive({ key:'', label:'', field_type:'text', options:'', required:false, active:true, sort_order:0 })

function normalizeValue(field, value){ return field.field_type==='checkbox' ? value==='true'||value===true : (value ?? '') }
async function loadDefinitions(){ if(!props.admin)return; fields.value=await api.contactFields() }
async function loadValues(){ if(!props.contact){fields.value=[];return} loading.value=true;error.value='';try{const rows=await api.contactCustomFields(props.contact.id);fields.value=rows;for(const f of rows)values[f.id]=normalizeValue(f,f.value)}catch(e){error.value=e.message}finally{loading.value=false} }
async function saveValue(field){saving.value={...saving.value,[field.id]:true};error.value='';success.value='';try{const row=await api.setContactCustomField(props.contact.id,field.id,values[field.id]);values[field.id]=normalizeValue(row,row.value);success.value=`${field.label} saved.`}catch(e){error.value=e.message}finally{saving.value={...saving.value,[field.id]:false}}}
async function createField(){error.value='';success.value='';try{const payload={...form,options:form.field_type==='select'?form.options.split('\n').map(v=>v.trim()).filter(Boolean):[]};await api.createContactField(payload);Object.assign(form,{key:'',label:'',field_type:'text',options:'',required:false,active:true,sort_order:fields.value.length});await loadDefinitions();success.value='Contact field created.'}catch(e){error.value=e.message}}
async function toggleField(field){error.value='';try{await api.updateContactField(field.id,{active:!field.active});await loadDefinitions()}catch(e){error.value=e.message}}
async function removeField(field){if(!confirm(`Delete custom field “${field.label}” and its stored values?`))return;error.value='';try{await api.deleteContactField(field.id);await loadDefinitions()}catch(e){error.value=e.message}}
watch(()=>props.contact?.id,loadValues,{immediate:true})
onMounted(()=>{if(props.admin&&!props.contact)loadDefinitions()})
</script>

<template>
<section v-if="contact" class="contact-section custom-fields-section"><div class="section-title"><div><p class="eyebrow">Profile data</p><h3>Custom fields</h3></div><span>{{fields.length}}</span></div><div v-if="loading" class="empty-notes">Loading custom fields…</div><div v-else-if="!fields.length" class="empty-notes">No custom fields configured yet.</div><div v-else class="custom-fields-grid"><label v-for="field in fields" :key="field.id">{{field.label}} <i v-if="field.required">required</i><textarea v-if="field.field_type==='textarea'" v-model="values[field.id]" rows="3" @blur="saveValue(field)"/><select v-else-if="field.field_type==='select'" v-model="values[field.id]" @change="saveValue(field)"><option value="">— Select —</option><option v-for="option in field.options" :key="option" :value="option">{{option}}</option></select><span v-else-if="field.field_type==='checkbox'" class="checkbox-field"><input v-model="values[field.id]" type="checkbox" @change="saveValue(field)"/> Yes</span><input v-else v-model="values[field.id]" :type="field.field_type==='number'?'number':field.field_type==='date'?'date':field.field_type==='email'?'email':'text'" @blur="saveValue(field)"/><small v-if="saving[field.id]">Saving…</small></label></div><p v-if="success" class="success-message">{{success}}</p><p v-if="error" class="form-error">{{error}}</p></section>

<section v-else-if="admin" class="settings-card wide-card contact-fields-admin"><div class="section-title"><div><p class="eyebrow">Contact data</p><h2>Custom contact fields</h2><p class="muted">Define reusable fields that agents can maintain on every contact profile.</p></div></div><form class="custom-field-create" @submit.prevent="createField"><div class="form-grid"><label>Label<input v-model="form.label" required placeholder="Company"/></label><label>Key<input v-model="form.key" required pattern="[a-z0-9_-]+" placeholder="company"/></label><label>Type<select v-model="form.field_type"><option value="text">Text</option><option value="textarea">Long text</option><option value="email">Email</option><option value="number">Number</option><option value="date">Date</option><option value="select">Select</option><option value="checkbox">Checkbox</option></select></label><label>Sort order<input v-model.number="form.sort_order" type="number"/></label><label v-if="form.field_type==='select'" class="wide">Options (one per line)<textarea v-model="form.options" rows="4" required/></label></div><label class="inline-check"><input v-model="form.required" type="checkbox"/> Required</label><button class="primary">Create field</button></form><div class="field-definition-list"><article v-for="field in fields" :key="field.id" class="field-definition-row"><div><strong>{{field.label}}</strong><span>{{field.key}} · {{field.field_type}}<template v-if="field.required"> · required</template></span></div><span class="status-pill" :class="{inactive:!field.active}">{{field.active?'active':'inactive'}}</span><button class="secondary" @click="toggleField(field)">{{field.active?'Disable':'Enable'}}</button><button class="secondary danger" @click="removeField(field)">Delete</button></article><div v-if="!fields.length" class="empty-notes">No custom fields defined yet.</div></div><p v-if="success" class="success-message">{{success}}</p><p v-if="error" class="form-error">{{error}}</p></section>
</template>
