<script setup>
import {computed,onMounted,ref,watch} from 'vue'
import {api} from './api'
const props=defineProps({channel:{type:String,required:true}})
const loading=ref(false),saving=ref(''),error=ref(''),success=ref(''),rows=ref([]),flows=ref([])
const labels={location:['Location received','Run a flow when a user sends a location pin.'],image:['Image received','Run a flow for an unsolicited image, photo or sticker.'],video:['Video received','Run a flow for an unsolicited video.'],audio:['Voice / audio received','Run a flow for an unsolicited voice note or audio file.'],document:['Document / file received','Run a flow for an unsolicited document or file.'],contact:['Contact received','Run a flow when a user shares a contact.'],unmatched_text:['Unmatched text','Fallback when text did not match a keyword or another active interaction.']}
const vars={location:['%inbound.latitude%','%inbound.longitude%','%inbound.location%'],image:['%inbound.url%','%inbound.mime_type%','%inbound.caption%'],video:['%inbound.url%','%inbound.mime_type%','%inbound.caption%'],audio:['%inbound.url%','%inbound.mime_type%','%inbound.filename%'],document:['%inbound.url%','%inbound.mime_type%','%inbound.filename%'],contact:['%inbound.contact_name%','%inbound.contact_phone%','%inbound.contact_user_id%'],unmatched_text:['%inbound.text%']}
const title=computed(()=>props.channel==='telegram'?'Telegram':'WhatsApp')
async function load(){loading.value=true;error.value='';try{[rows.value,flows.value]=await Promise.all([api.defaultActions(props.channel),api.defaultActionFlows(props.channel)])}catch(e){error.value=e.message}finally{loading.value=false}}
async function save(row){saving.value=row.action_type;error.value='';success.value='';try{const saved=await api.setDefaultAction(props.channel,row.action_type,{flow_id:row.flow_id?Number(row.flow_id):null,enabled:!!row.enabled});Object.assign(row,saved);success.value=`${labels[row.action_type]?.[0]||row.action_type} saved.`}catch(e){error.value=e.message}finally{saving.value=''}}
function changed(row){if(!row.flow_id)row.enabled=false;else if(row.enabled===false){}else row.enabled=true}
watch(()=>props.channel,load);onMounted(load)
</script>

<template><section class="default-actions-page"><header><div><p class="eyebrow">{{title}}</p><h1>Default Actions</h1><p>Choose which flow should handle inbound events that are not already owned by an active interaction.</p></div><button class="refresh" @click="load">↻ Refresh</button></header><div v-if="error" class="notice error">{{error}}</div><div v-if="success" class="notice success">{{success}}</div><div class="priority-note"><strong>Routing priority</strong><span>Active flow replies → keyword / first-message triggers → Default Actions. An event requested by a running flow therefore stays inside that flow.</span></div><div v-if="loading" class="empty">Loading Default Actions…</div><div v-else class="actions-list"><article v-for="row in rows" :key="row.action_type"><div class="action-copy"><strong>{{labels[row.action_type]?.[0]||row.action_type}}</strong><span>{{labels[row.action_type]?.[1]}}</span><div class="var-chips"><code v-for="token in vars[row.action_type]||[]" :key="token">{{token}}</code></div></div><label class="flow-field"><span>Flow</span><select v-model="row.flow_id" @change="changed(row)"><option :value="null">No flow assigned</option><option v-for="flow in flows" :key="flow.id" :value="flow.id">{{flow.name}}</option></select></label><label class="toggle"><input type="checkbox" v-model="row.enabled" :disabled="!row.flow_id"><span>Enabled</span></label><button class="save" :disabled="saving===row.action_type" @click="save(row)">{{saving===row.action_type?'Saving…':'Save'}}</button></article></div><footer><strong>Available inbound variables</strong><span><code>%inbound.type%</code> and <code>%inbound.channel%</code> are available to every Default Action. Media actions also support <code>%inbound.url%</code>, <code>%inbound.media_url%</code>, <code>%inbound.mime_type%</code>, <code>%inbound.filename%</code>, <code>%inbound.file_size%</code>, <code>%inbound.caption%</code> and <code>%inbound.media_id%</code> when supplied by the channel. Contact actions also expose <code>%inbound.contact_json%</code> and Telegram contact cards can expose <code>%inbound.contact_vcard%</code>.</span></footer></section></template>

<style scoped>.default-actions-page{margin-left:220px;min-height:100vh;padding:34px 38px;background:#f4f7f6;color:#13251d}.default-actions-page header{display:flex;justify-content:space-between;gap:20px;margin-bottom:22px}.eyebrow{margin:0;text-transform:uppercase;color:#119052;font-size:11px;font-weight:800;letter-spacing:.08em}.default-actions-page h1{font-size:30px;margin:3px 0 5px}.default-actions-page header p:last-child{margin:0;color:#74867e}.refresh{align-self:flex-start;border:1px solid #d5dfdb;background:#fff;border-radius:9px;padding:10px 14px}.notice{padding:11px 14px;border-radius:8px;margin-bottom:14px}.notice.error{background:#fff0f0;color:#9c2929}.notice.success{background:#eaf8ef;color:#176c3d}.priority-note{display:flex;flex-direction:column;gap:5px;background:#eef7f2;border:1px solid #cfe5d9;border-radius:12px;padding:15px 17px;margin-bottom:18px}.priority-note span{color:#60766c}.actions-list{display:flex;flex-direction:column;gap:10px}.actions-list article{display:grid;grid-template-columns:minmax(280px,1.4fr) minmax(260px,1fr) 110px 82px;gap:18px;align-items:center;background:#fff;border:1px solid #dce6e1;border-radius:12px;padding:17px}.action-copy strong,.action-copy span{display:block}.action-copy span{color:#74867e;font-size:13px;margin-top:4px}.var-chips{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.action-copy code{font-size:11px;color:#19734a;background:#eef8f2;padding:4px 6px;border-radius:5px}.flow-field span{display:block;font-size:11px;font-weight:700;text-transform:uppercase;color:#71847b;margin-bottom:5px}.flow-field select{width:100%;border:1px solid #ccd9d3;border-radius:8px;padding:9px;background:#fff}.toggle{display:flex;align-items:center;gap:7px;font-size:13px}.toggle input{width:17px;height:17px}.save{border:0;background:#16834f;color:#fff;border-radius:8px;padding:10px 13px;font-weight:700}.save:disabled{opacity:.55}.empty{background:#fff;border:1px solid #dce6e1;border-radius:12px;padding:25px;color:#71847b}.default-actions-page footer{display:flex;flex-direction:column;gap:6px;margin-top:20px;color:#60766c;font-size:13px;line-height:1.65}.default-actions-page footer strong{color:#243d32}.default-actions-page footer code{background:#e7efeb;padding:2px 5px;border-radius:4px}@media(max-width:1100px){.actions-list article{grid-template-columns:1fr 1fr}.save{width:82px}} </style>