<script setup>
import { computed,ref,watch } from 'vue'
const props=defineProps({draft:{type:Object,required:true},fields:{type:Array,default:()=>[]},direct:{type:Boolean,default:false}})
const advanced=ref(false)
const descriptionParts=ref([])
const commonKeys=['product_name','name','title','price','description','buy_link','url','id','value','code','label']
const fieldOptions=computed(()=>{const seen=new Set(),out=[];for(const key of commonKeys){if(!seen.has(key)){seen.add(key);out.push(key)}}for(const key of [props.draft.dynamic_title_path,props.draft.dynamic_value_path]){if(key&&!seen.has(key)){seen.add(key);out.push(key)}}return out})
function syncSource(){const f=props.fields.find(x=>String(x.id)===String(props.draft.dynamic_source_field_id));props.draft.dynamic_source_field_key=f?.key||''}
function syncTarget(){const f=props.fields.find(x=>String(x.id)===String(props.draft.dynamic_save_field_id));props.draft.dynamic_save_field_key=f?.key||''}
function parseDescription(value){const text=String(value||'');const parts=[];const re=/\{\{\s*item\.([^}]+?)\s*\}\}/g;let last=0,m;while((m=re.exec(text))){if(m.index>last)parts.push({type:'text',value:text.slice(last,m.index)});parts.push({type:'field',value:m[1].trim()});last=re.lastIndex}if(last<text.length)parts.push({type:'text',value:text.slice(last)});return parts.length?parts:[]}
function buildDescription(){props.draft.dynamic_description=descriptionParts.value.map(p=>p.type==='field'?`{{item.${p.value}}}`:p.value).join('')}
function addDescriptionField(){descriptionParts.value.push({type:'field',value:'description'});buildDescription()}
function addDescriptionText(){descriptionParts.value.push({type:'text',value:' - '});buildDescription()}
function removePart(i){descriptionParts.value.splice(i,1);buildDescription()}
watch(()=>props.draft.dynamic_description,v=>{const built=descriptionParts.value.map(p=>p.type==='field'?`{{item.${p.value}}}`:p.value).join('');if(String(v||'')!==built)descriptionParts.value=parseDescription(v)},{immediate:true})
</script>
<template>
<section class="dynamic-list">
<div class="intro"><strong>List Content</strong><p>Choose where the choices come from and how each option should look.</p></div>
<label>Content source<select v-model="draft.row_generation"><option value="static">Static choices from connected blocks</option><option value="dynamic">Dynamic choices from API / JSON</option></select></label>
<template v-if="draft.row_generation==='dynamic'">
<div class="section-title"><span>1</span><div><strong>Data source</strong><small>Select the custom field containing your API response or JSON list.</small></div></div>
<label>JSON data<select v-model="draft.dynamic_source_field_id" @change="syncSource"><option value="">— Select data source —</option><option v-for="f in fields" :key="f.id" :value="f.id">{{f.label||f.name||f.key}} · %{{f.key}}%</option></select></label>
<div class="section-title"><span>2</span><div><strong>List row</strong><small>Choose what the subscriber sees and what value is returned when they select it.</small></div></div>
<label>Title<select v-model="draft.dynamic_title_path"><option value="">— Select JSON field —</option><option v-for="key in fieldOptions" :key="key" :value="key">{{key}}</option></select><small>The main label shown for each option.</small></label>
<label>Description <small>Optional. Build the subtitle from JSON fields and text.</small></label>
<div class="parts" v-if="descriptionParts.length"><div v-for="(part,i) in descriptionParts" :key="i" class="part"><template v-if="part.type==='field'"><span class="badge">FIELD</span><select v-model="part.value" @change="buildDescription"><option v-for="key in fieldOptions" :key="key" :value="key">{{key}}</option></select></template><template v-else><span class="badge text">TEXT</span><input v-model="part.value" @input="buildDescription" placeholder=" - "></template><button type="button" @click="removePart(i)">×</button></div></div>
<div class="part-actions"><button type="button" @click="addDescriptionField">＋ Add field</button><button type="button" @click="addDescriptionText">＋ Add text</button></div>
<label>Value when selected<select v-model="draft.dynamic_value_path"><option value="">— Same as title —</option><option v-for="key in fieldOptions" :key="key" :value="key">{{key}}</option></select><small>This is the value that can be saved and used by the next flow blocks.</small></label>
<div class="section-title"><span>3</span><div><strong>After selection</strong><small>Choose where WA Connect should store the selected value.</small></div></div>
<label>Save selected value to<select v-model="draft.dynamic_save_field_id" @change="syncTarget"><option value="">— Do not save —</option><option v-for="f in fields" :key="f.id" :value="f.id">{{f.label||f.name||f.key}} · %{{f.key}}%</option></select></label>
<label class="check"><input v-model="draft.dynamic_save_entire_object" type="checkbox"> Save the entire selected item instead of only the selected value</label>
<button class="advanced-toggle" type="button" @click="advanced=!advanced">{{advanced?'▾':'▸'}} Advanced options</button>
<div v-if="advanced" class="advanced"><label>Array path<input v-model="draft.dynamic_array_path" placeholder="Leave blank for entire response"><small>Only needed when the list is nested, e.g. <code>data.products</code>.</small></label><label>Raw description template<input v-model="draft.dynamic_description" placeholder="{{item.price}} - {{item.description}}"><small>Advanced template syntax. The visual description builder above updates this automatically.</small></label><div class="keys"><b>Field keys</b><span>Title: <code>{{draft.dynamic_title_path||'—'}}</code></span><span>Value: <code>{{draft.dynamic_value_path||draft.dynamic_title_path||'—'}}</code></span><span v-if="draft.dynamic_source_field_key">Source: <code>%{{draft.dynamic_source_field_key}}%</code></span><span v-if="draft.dynamic_save_field_key">Save to: <code>%{{draft.dynamic_save_field_key}}%</code></span></div></div>
<div class="preview"><b>Row preview</b><strong>{{draft.dynamic_title_path?`{ ${draft.dynamic_title_path} }`:'Choose a title field'}}</strong><span v-if="draft.dynamic_description">{{draft.dynamic_description.replace(/\{\{\s*item\.([^}]+?)\s*\}\}/g,'{ $1 }')}}</span><small>Selected value → {{draft.dynamic_save_entire_object?'Entire item':(draft.dynamic_value_path||draft.dynamic_title_path||'not configured')}}</small></div>
</template></section>
</template>
<style scoped>
.dynamic-list{border:1px solid #dbe7e2;border-radius:12px;padding:14px;margin:14px 0;background:#f9fcfb}.intro{margin-bottom:14px}.intro strong{font-size:15px}.intro p{font-size:12px;color:#6b7d76;margin:4px 0 0}.dynamic-list label{margin:10px 0}.dynamic-list small{font-weight:400;color:#71817b}.section-title{display:flex;gap:9px;align-items:flex-start;margin:18px 0 8px;padding-top:14px;border-top:1px solid #e3ece8}.section-title>span{display:grid;place-items:center;width:23px;height:23px;border-radius:50%;background:#168f55;color:white;font-size:11px;font-weight:800;flex:0 0 auto}.section-title strong,.section-title small{display:block}.parts{display:flex;flex-direction:column;gap:6px;margin-top:6px}.part{display:grid;grid-template-columns:48px minmax(0,1fr) 32px;gap:5px;align-items:center}.part select,.part input{min-width:0;width:100%;box-sizing:border-box}.part button{height:35px;border:0;border-radius:7px;background:#fff0f0;color:#a33}.badge{font-size:8px;font-weight:800;color:#17764a;background:#e5f7ed;padding:5px 4px;border-radius:5px;text-align:center}.badge.text{color:#5f6e67;background:#edf1ef}.part-actions{display:flex;gap:6px;margin:7px 0 12px}.part-actions button,.advanced-toggle{border:1px solid #b9d9ca;background:#fff;border-radius:7px;padding:7px 9px;color:#176b46;font-weight:700;cursor:pointer}.check{flex-direction:row!important;align-items:center}.check input{width:auto}.advanced-toggle{width:100%;text-align:left;margin-top:12px}.advanced{margin-top:8px;padding:10px;background:#f1f6f4;border-radius:8px}.keys{font-size:11px;display:flex;flex-direction:column;gap:3px;margin-top:9px}.preview{margin-top:12px;background:#eef8f3;border-radius:8px;padding:11px;display:flex;flex-direction:column;gap:4px}.preview>b{font-size:10px;text-transform:uppercase;color:#5d786a}.preview>strong{font-size:13px}.preview>span,.preview>small{font-size:11px;color:#687c72}
</style>