<script setup>
import { computed, ref } from 'vue'
const props=defineProps({fields:{type:Array,default:()=>[]},inputVariables:{type:Array,default:()=>[]}})
const emit=defineEmits(['insert'])
const open=ref(false),search=ref(''),discovered=ref([])
const inboundVariables=[
  {key:'type',label:'Inbound event type'},{key:'channel',label:'Inbound channel'},{key:'text',label:'Unmatched text'},
  {key:'latitude',label:'Location latitude'},{key:'longitude',label:'Location longitude'},{key:'location',label:'Combined location'},
  {key:'url',label:'Stored media URL'},{key:'media_url',label:'Stored media URL (alias)'},{key:'mime_type',label:'Media MIME type'},
  {key:'filename',label:'Media filename'},{key:'file_size',label:'Media file size'},{key:'caption',label:'Media caption'},{key:'media_id',label:'Native media ID'},
  {key:'contact_name',label:'Shared contact name'},{key:'contact_phone',label:'Shared contact phone'},{key:'contact_user_id',label:'Shared contact user ID'},
  {key:'contact_vcard',label:'Shared contact vCard'},{key:'contact_json',label:'Shared contact JSON'}
]
function matches(item,q){const label=String(item.label||item.name||item.key||''),key=String(item.key||'');return !q||label.toLowerCase().includes(q)||key.toLowerCase().includes(q)}
function discover(){const found=[];document.querySelectorAll('.node').forEach(node=>{const icon=node.querySelector('header span')?.textContent?.trim(),key=node.querySelector('header strong')?.textContent?.trim();if(icon==='❓'&&key&&key.toLowerCase()!=='question'&&!found.some(x=>x.key===key))found.push({key,label:key})});discovered.value=found}
function toggle(){open.value=!open.value;if(open.value)discover()}
const availableInputs=computed(()=>props.inputVariables.length?props.inputVariables:discovered.value)
const filteredInputs=computed(()=>{const q=search.value.trim().toLowerCase();return availableInputs.value.filter(v=>matches(v,q))})
const filteredFields=computed(()=>{const q=search.value.trim().toLowerCase();return props.fields.filter(f=>matches(f,q))})
const filteredInbound=computed(()=>{const q=search.value.trim().toLowerCase();return inboundVariables.filter(v=>matches(v,q))})
const showCampaign=computed(()=>{const q=search.value.trim().toLowerCase();return !q||'campaign answers questionnaire json'.includes(q)})
function choose(token){if(!token)return;emit('insert',token);open.value=false;search.value=''}
</script>
<template><div class="variable-insert"><button type="button" class="insert-button" @click="toggle">＋ Insert Variable</button><div v-if="open" class="variable-menu"><div class="menu-head"><b>Insert variable</b><button type="button" @click="open=false">×</button></div><input v-model="search" placeholder="Search variables…" autofocus><div class="variable-list"><template v-if="filteredInbound.length"><div class="section-title">Inbound / Default Actions</div><button v-for="item in filteredInbound" :key="'inbound-'+item.key" type="button" @click="choose(`%inbound.${item.key}%`)"><span>{{item.label}}</span><code>%inbound.{{item.key}}%</code></button></template><template v-if="showCampaign"><div class="section-title">Campaign</div><button type="button" @click="choose('%campaign.answers%')"><span>Campaign answers (JSON)</span><code>%campaign.answers%</code></button></template><template v-if="filteredInputs.length"><div class="section-title">User input</div><button v-for="item in filteredInputs" :key="'input-'+item.key" type="button" @click="choose(`%input.${item.key}%`)"><span>{{item.label||item.key}}</span><code>%input.{{item.key}}%</code></button></template><template v-if="filteredFields.length"><div class="section-title">Custom fields</div><button v-for="field in filteredFields" :key="field.id||field.key" type="button" @click="choose(`%${field.key}%`)"><span>{{field.label||field.name||field.key}}</span><code>%{{field.key}}%</code></button></template><p v-if="!filteredInbound.length&&!showCampaign&&!filteredInputs.length&&!filteredFields.length">No matching variables.</p></div><small><code>%inbound.*%</code> values belong to the current Default Action event; campaign and User Input values belong to submissions; custom fields belong to the contact.</small></div></div></template>
<style scoped>.variable-insert{position:relative;margin-top:7px}.insert-button{border:1px solid #cfe3d9!important;background:#f3faf6!important;color:#167348;padding:7px 10px!important;border-radius:7px!important;font-size:11px;font-weight:700;cursor:pointer}.variable-menu{position:absolute;z-index:90;left:0;top:38px;width:330px;background:#fff;border:1px solid #d8e4df;border-radius:10px;box-shadow:0 12px 30px rgba(20,45,35,.18);padding:10px}.menu-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.menu-head button{border:0!important;background:none!important;font-size:18px;cursor:pointer}.variable-menu>input{width:100%;box-sizing:border-box;margin-bottom:8px}.variable-list{max-height:300px;overflow:auto}.section-title{padding:9px 9px 5px;color:#6d8078;font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;background:#f8faf9}.variable-list button{display:flex!important;flex-direction:column!important;align-items:flex-start!important;gap:2px!important;width:100%;border:0!important;border-bottom:1px solid #edf2ef!important;background:#fff!important;padding:9px!important;text-align:left;cursor:pointer}.variable-list button:hover{background:#f2faf6!important}.variable-list span{font-size:12px;font-weight:700}.variable-list code{font-size:10px;color:#168653}.variable-list p{font-size:11px;color:#7c8b85;padding:8px}.variable-menu>small{display:block;margin-top:8px;color:#7c8b85;font-size:10px;line-height:1.35}</style>